server:
  port: 8782
spring:
  application:
    name: springclouddemoconsumerfeign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true